spring:
  application:
    name: daw2-config-repo
  datasource:
    url: jdbc:mysql://localhost:3306/vetmarket
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0
