spring:
  application:
    name: Servicio

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # ✅ Configuración para subida de archivos (HTTP)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
app:
  topic:
    name: servicio-notification
